version: "3.9"
services:
  resource-service:
    build:
      context: ./resource-service
    environment:
      SPRING_APPLICATION_NAME: "${RESOURCE_SERVICE_NAME}"
      SERVER_PORT: "${RESOURCE_SERVICE_PORT}"
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "${EUREKA_CLIENT_SERVICEURL}"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://resources-db:5432/${POSTGRES_DB_RESOURCES}"
      SPRING_DATASOURCE_USERNAME: "${POSTGRES_USER_RESOURCES}"
      SPRING_DATASOURCE_PASSWORD: "${POSTGRES_PASSWORD_RESOURCES}"
      LOCAL_RESOURCES_PATH: "/resources"
      SPRING_RABBITMQ_HOST: "rabbitmq"  # Ensure RabbitMQ host matches the service name
      SPRING_RABBITMQ_PORT: "5672"
      SPRING_RABBITMQ_USERNAME: "test"
      SPRING_RABBITMQ_PASSWORD: "test"
      CLOUD_AWS_CREDENTIALS_ACCESS_KEY: "${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}"
      CLOUD_AWS_CREDENTIALS_SECRET_KEY: "${CLOUD_AWS_CREDENTIALS_SECRET_KEY}"
      CLOUD_AWS_REGION_STATIC: "${CLOUD_AWS_REGION_STATIC}"
      CLOUD_AWS_S3_STAGING_BUCKET_NAME: "${CLOUD_AWS_S3_STAGING_BUCKET_NAME}"
      CLOUD_AWS_S3_PERMANENT_BUCKET_NAME: "${CLOUD_AWS_S3_PERMANENT_BUCKET_NAME}"
      CLOUD_AWS_S3_ENDPOINT: "${CLOUD_AWS_S3_ENDPOINT}"
      RESOURCE_RABBITMQ_EXCHANGE: "${RESOURCE_RABBITMQ_EXCHANGE}"
      RESOURCE_RABBITMQ_QUEUE: "${RESOURCE_RABBITMQ_QUEUE}"
    command: [ "dockerize", "-wait", "tcp://configuration-server:${CONFIG_SERVER_PORT}", "-timeout", "1m", "java", "-jar", "resource-service.jar" ]
    depends_on:
      - configuration-server
      - discovery-server
      - resources-db
      - storage-service
      - rabbitmq
    networks:
      - app-network

  storage-service:
    build:
      context: ./storage-service
      dockerfile: Dockerfile
    environment:
      SPRING_APPLICATION_NAME: "${STORAGE_SERVICE_NAME}"
      SERVER_PORT: "${STORAGE_SERVICE_PORT}"
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "${EUREKA_CLIENT_SERVICEURL}"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://storage-db:5432/${POSTGRES_DB_STORAGE}"
      SPRING_DATASOURCE_USERNAME: "${POSTGRES_USER_STORAGE}"
      SPRING_DATASOURCE_PASSWORD: "${POSTGRES_PASSWORD_STORAGE}"
    command: [ "dockerize", "-wait", "tcp://configuration-server:${CONFIG_SERVER_PORT}", "-timeout", "1m", "java", "-jar", "storage-service.jar" ]
    depends_on:
      - configuration-server
      - discovery-server
      - storage-db
    networks:
      - app-network

  song-service:
    build:
      context: ./song-service
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: "${SONG_SERVICE_PORT}"
      SPRING_APPLICATION_NAME: "${SONG_SERVICE_NAME}"
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "${EUREKA_CLIENT_SERVICEURL}"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://songs-db:5432/${POSTGRES_DB_SONGS}"
      SPRING_DATASOURCE_USERNAME: "${POSTGRES_USER_SONGS}"
      SPRING_DATASOURCE_PASSWORD: "${POSTGRES_PASSWORD_SONGS}"
    command: ["dockerize", "-wait", "tcp://configuration-server:${CONFIG_SERVER_PORT}", "-timeout", "1m", "java", "-jar", "song-service.jar"]
    depends_on:
      - configuration-server
      - discovery-server
      - songs-db
    networks:
      - app-network

  discovery-server:
    build: ./discovery-server
    ports:
      - "${EUREKA_SERVER_PORT}:${EUREKA_SERVER_PORT}"
    environment:
      SPRING_APPLICATION_NAME: "${DISCOVERY_SERVICE_NAME}"
      SERVER_PORT: "${EUREKA_SERVER_PORT}"
    command: ["dockerize", "-wait", "tcp://configuration-server:${CONFIG_SERVER_PORT}", "-timeout", "1m", "java", "-jar", "discovery-server.jar"]
    depends_on:
      - configuration-server
      - resources-db
      - songs-db
    networks:
      - app-network

  resource-processor:
    build:
      context: ./resource-processor
    environment:
      SPRING_APPLICATION_NAME: "${RESOURCE_PROCESSOR_NAME}"
      SERVER_PORT: "${RESOURCE_PROCESSOR_PORT}"
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "${EUREKA_CLIENT_SERVICEURL}"
      SPRING_RABBITMQ_HOST: "rabbitmq"  # Ensure consistency
      SPRING_RABBITMQ_PORT: "5672"
      SPRING_RABBITMQ_USERNAME: "test"
      SPRING_RABBITMQ_PASSWORD: "test"
    command: [ "dockerize", "-wait", "tcp://configuration-server:${CONFIG_SERVER_PORT}", "-timeout", "1m", "java", "-jar", "resource-processor.jar" ]
    depends_on:
      - configuration-server
      - discovery-server
      - resource-service
      - rabbitmq
    networks:
      - app-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    environment:
      SPRING_APPLICATION_NAME: "${API_GATEWAY_NAME}"
      SERVER_PORT: "${API_GATEWAY_PORT}"
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: "${EUREKA_CLIENT_SERVICEURL}"
    command: ["dockerize", "-wait", "tcp://configuration-server:${CONFIG_SERVER_PORT}", "-timeout", "1m", "java", "-jar", "api-gateway.jar"]
    depends_on:
      - configuration-server
    networks:
      - app-network

  configuration-server:
    build: ./configuration-server
    ports:
      - "${CONFIG_SERVER_PORT}:${CONFIG_SERVER_PORT}"
    environment:
      SPRING_APPLICATION_NAME: "${CONFIG_SERVER_NAME}"
      SERVER_PORT: "${CONFIG_SERVER_PORT}"
    networks:
      - app-network

  resources-db:
    image: postgres:14-alpine
    ports:
      - "${POSTGRES_PORT_RESOURCES}:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER_RESOURCES}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD_RESOURCES}"
      POSTGRES_DB: "${POSTGRES_DB_RESOURCES}"
    networks:
      - app-network

  songs-db:
    image: postgres:14-alpine
    ports:
      - "${POSTGRES_PORT_SONGS}:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER_SONGS}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD_SONGS}"
      POSTGRES_DB: "${POSTGRES_DB_SONGS}"
    volumes:
      - ./db/init-songs.sql:/docker-entrypoint-initdb.d/init-songs.sql
      - ./resources:/resources
    networks:
      - app-network

  storage-db:
    image: postgres:14-alpine
    ports:
      - "${POSTGRES_PORT_STORAGE}:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER_STORAGE}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD_STORAGE}"
      POSTGRES_DB: "${POSTGRES_DB_STORAGE}"
    volumes:
      - ./db/init-storage.sql:/docker-entrypoint-initdb.d/init-storage.sql
    networks:
      - app-network

  localstack:
    image: localstack/localstack
    ports:
      - "4510:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge