spring.application.name=resource-processor
server.port=8084
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

management.endpoints.web.exposure.include=*

# Logging configuration
logging.level.root=INFO
logging.level.org.springframework=INFO