tasks.bootJar {
	enabled = true
	mainClass = 'com.krystseu.microservices.resourceprocessor.ResourceProcessorApplication'
}

dependencies {
	implementation 'org.apache.tika:tika-core:2.9.2'
	implementation 'org.apache.tika:tika-parser-audiovideo-module:2.9.2'
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-web'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}